spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/${db_name}
    username: ${db_user}
    password: ${db_password}
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true